stages:
  - test

include:
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml

# Customize behavior globally using variables
variables:
  # Common SAST settings
  SAST_EXCLUDED_PATHS: "spec, test, tests, tmp, node_modules"
  
  # Common Secret Detection settings
  SECRET_DETECTION_HISTORIC_SCAN: "false" # Set to "true" to scan all git history (slower)